apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxtestkusto
  namespace: flux-system
spec:
  interval: 10s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxtest
