---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxtestkustodemo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: kustodemo
  url: https://github.com/MahammadRafi06/flux_test
