---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: medicalrepo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: medicalrepo-auth
  url: ssh://git@github.com/MahammadRafi06/ReAct-Agents-Coding-Workflows
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: medicalrepokusto
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: medicalrepo
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: medicalcoderimagerepo
  namespace: flux-system
spec:
  image: docker.io/mrafit20/medicalcoder
  interval: 10s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: medicalcodeimagepolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: medicalcoderimagerepo
  policy:
    semver:
      range: 1.0.x

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: medicalrepoimageupdate
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: medicalrepo
  update:
    path: ./manifests
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-webhook-receiver
  namespace: flux-system
spec:
  events:
  - ping
  - push
  resources:
  - kind: GitRepository
    name: medicalrepo
  secretRef:
    name: github-webhook
  type: github