---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoringrepo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: medicalrepo
  url: ssh://git@github.com/MahammadRafi06/flux2-monitoring-aks

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 10s
  retryInterval: 2s
  timeout: 8s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: montoringrepo
  path: ./monitoring/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 10s
  retryInterval: 2s
  timeout: 5s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: montoringrepo
  path: ./monitoring/configs