apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp 
  namespace: default
  labels:
    name: myapp-deploy
    tyre: fronend 
spec:
  selector:
    matchLabels:
        app: medicalcoder
        tier: front-end      
  replicas: 1
  template:
    metadata: 
      name: up
      labels:
        app: medicalcoder
        tier: front-end

    spec:
      containers:
        - name: medicalcoder
          image: mrafit20/medicalcoder:1.0.1
          ports:
            - containerPort: 5000

