apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-1gb
  namespace: 2demo
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
